export const sample_foods = [
    {
        id: '1',
        name: 'Pizza Pasta',
        cookTime: '1 hour',
        price: '100',
        favorite: true,
        origins: ['Italian', 'American'],
        stars: 4,
        imageUrl: '/foods/food-1.jpg',
        tags: ['Pasta', 'Pizza', 'italian'],
    },
    {
        id: '2',
        name: 'Meatball Pasta',
        cookTime: '1 hour',
        price: '100',
        favorite: true,
        origins: ['Italian', 'American'],
        stars: 2.5,
        imageUrl: '/foods/food-2.jpg',
        tags: ['pasta', 'pizza', 'italian'],
    },
    {
        id: '3',
        name: 'Hamburger',
        cookTime: '1 hour',
        price: '100',
        favorite: true,
        origins: ['Italian', 'American'],
        stars: 4,
        imageUrl: '/foods/food-3.jpg',
        tags: ['pasta', 'pizza', 'italian'],
    },
    {
        id: '4',
        name: 'Fried Chicken',
        cookTime: '1 hour',
        price: '100',
        favorite: true,
        origins: ['Italian', 'American'],
        stars: 4,
        imageUrl: '/foods/food-4.jpg',
        tags: ['pasta', 'pizza', 'italian'],
    },
    {
        id: '5',
        name: 'Chicken Soup',
        cookTime: '1 hour',
        price: '100',
        favorite: true,
        origins: ['Italian', 'American'],
        stars: 4,
        imageUrl: '/foods/food-1.jpg',
        tags: ['pasta', 'pizza', 'italian'],
    },
    {
        id: '6',
        name: 'vegetable Pizza',
        cookTime: '1 hour',
        price: '100',
        favorite: true,
        origins: ['Italian', 'American'],
        stars: 4,
        imageUrl: '/foods/food-2.jpg',
        tags: ['pasta', 'pizza', 'italian'],
    },
    {
        id: '7',
        name: 'asian Pizza',
        cookTime: '1 hour',
        price: '100',
        favorite: true,
        origins: ['Italian', 'American'],
        stars: 4,
        imageUrl: '/foods/food-3.jpg',
        tags: ['pasta', 'pizza', 'italian'],
    },
    {
        id: '8',
        name: 'beef Pizza',
        cookTime: '1 hour',
        price: '100',
        favorite: true,
        origins: ['Italian', 'American'],
        stars: 3.5,
        imageUrl: '/foods/food-4.jpg',
        tags: ['pasta', 'pizza', 'italian'],
    },
]

export const sample_tags = [
    {name: 'All', count: 8},
    {name: 'FastFood', count: 4},
    {name: 'Pizza', count: 4},
    {name: 'Chicken', count: 6},
    {name: 'Hamburger', count: 1},
    {name: 'Soup', count: 1},
    {name: 'Breakfast', count: 1},
    {name: 'Drinks', count: 1},
]
